replicaCount: 3

image:
  repository: mpolden/echoip
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingressType: traefik
host: echoip.example.com

port: 8080
listenAddr: ":8080"

useGeoDb: true
useReverseLookup: true
usePortLookup: true
trustedHeader: "X-Forwarded-For"

storageClassName: azurefile
