replicaCount: 1

image:
  repository: maximbaz/ipd
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingressType: traefik
host: ipd.example.com

port: 8080
listenAddr: ":8080"

useGeoDb: true
useReverseLookup: true
usePortLookup: true
trustedHeader: "X-Forwarded-For"
