apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "echoip.fullname" . }}-tools
  labels:
    app: {{ template "echoip.name" . }}
    chart: {{ template "echoip.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  liveness.sh: |
{{ .Files.Get "files/liveness.sh" | indent 4 }}
  update-db.sh: |
{{ .Files.Get "files/update-db.sh" | indent 4 }}
  init-db.sh: |
{{ .Files.Get "files/init-db.sh" | indent 4 }}
  entrypoint.sh: |
{{ .Files.Get "files/entrypoint.sh" | indent 4 }}
