apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ipd.fullname" . }}-tools
  labels:
    app: {{ template "ipd.name" . }}
    chart: {{ template "ipd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  liveness.sh: |
{{ .Files.Get "files/liveness.sh"  | indent 4 }}
  update-db.sh: |
{{ .Files.Get "files/update-db.sh"  | indent 4 }}
