apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ipd.fullname" . }}-init-tools
  labels:
    app: {{ template "ipd.name" . }}
    chart: {{ template "ipd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  init-db.sh: |
{{ .Files.Get "files/init-db.sh"  | indent 4 }}
