{{ if .Values.useGeoDb }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "echoip.fullname" . }}-update-db
  labels:
    app: {{ template "echoip.name" . }}
    chart: {{ template "echoip.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  schedule: "0 12 8 * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: {{ template "echoip.fullname" . }}-update-db
              image: busybox
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command: ["/tools/update-db.sh"]
              envFrom:
                - secretRef:
                  name: {{ template "echoip.name " . }}-secret
              volumeMounts:
                - mountPath: /tools
                  name: tools-volume
                - mountPath: /db-shared
                  name: db-shared-volume
          volumes:
            - name: tools-volume
              configMap:
                name: {{ template "echoip.fullname" . }}-tools
                defaultMode: 0744
            - name: db-shared-volume
              persistentVolumeClaim:
                claimName: {{ template "echoip.fullname" . }}-db
{{ end }}
