apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "echoip.fullname" . }}
  labels:
    app: {{ template "echoip.name" . }}
    chart: {{ template "echoip.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "echoip.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "echoip.name" . }}
        release: {{ .Release.Name }}
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/tools/entrypoint.sh"]
          args:
            {{ if .Values.useGeoDb }}
            - -g
            {{ end }}
            {{ if .Values.useReverseLookup }}
            - -r
            {{ end }}
            {{ if .Values.usePortLookup }}
            - -p
            {{ end }}
            {{ if .Values.listenAddr }}
            - -l {{ .Values.listenAddr }}
            {{ end }}
            {{ if .Values.templateFilePath }}
            - -t {{ .Values.templateFilePath }}
            {{ end }}
            {{ if .Values.trustedHeader }}
            - -h {{ .Values.trustedHeader }}
            {{ end }}
          ports:
            - name: http
              containerPort: {{ .Values.port }}
              protocol: TCP
          volumeMounts:
            - mountPath: /tools
              name: tools-volume
          {{ if .Values.useGeoDb }}
            - mountPath: /db
              name: db-volume
            - mountPath: /db-shared
              name: db-shared-volume
          {{ end }}
          livenessProbe:
            exec:
              command:
                - '/tools/liveness.sh'
                - '{{ .Values.port }}'
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: tools-volume
          configMap:
            name: {{ template "echoip.fullname" . }}-tools
            defaultMode: 0755
        {{ if .Values.useGeoDb }}
        - name: db-volume
          emptyDir: {}
        - name: db-shared-volume
          persistentVolumeClaim:
            claimName: {{ template "echoip.fullname" . }}-db
        {{ end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
