apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "ipd.fullname" . }}
  labels:
    app: {{ template "ipd.name" . }}
    chart: {{ template "ipd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "ipd.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "ipd.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/opt/ipd"]
          args:
            {{ if .Values.countryDbPath }}
            - '--country-db={{ .Values.countryDbPath }}'
            {{ end }}
            {{ if .Values.cityDbPath }}
            - '--city-db={{ .Values.cityDbPath }}'
            {{ end }}
            {{ if .Values.listenAddr }}
            - '--listen={{ .Values.listenAddr }}'
            {{ end }}
            {{ if .Values.useReverseLookup }}
            - '--reverse-lookup'
            {{ end }}
            {{ if .Values.usePortLookup }}
            - '--port-lookup'
            {{ end }}
            {{ if .Values.templateFilePath }}
            - '--template-file="{{ .Values.templateFilePath }}"'
            {{ end }}
            {{ if .Values.trustedHeader }}
            - '--trusted-header="{{ .Values.trustedHeader }}"'
            {{ end }}
          ports:
            - name: http
              containerPort: {{ .Values.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
