apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "echoip.fullname" . }}
  labels:
    app: {{ template "echoip.name" . }}
    chart: {{ template "echoip.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "echoip.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "echoip.name" . }}
        release: {{ .Release.Name }}
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/opt/echoip"]
          args:
            {{ if .Values.useGeoDb }}
            - '--country-db=/db-shared/GeoLite2-Country.mmdb'
            - '--city-db=/db-shared/GeoLite2-City.mmdb'
            {{ end }}
            {{ if .Values.listenAddr }}
            - '--listen={{ .Values.listenAddr }}'
            {{ end }}
            {{ if .Values.useReverseLookup }}
            - '--reverse-lookup'
            {{ end }}
            {{ if .Values.usePortLookup }}
            - '--port-lookup'
            {{ end }}
            {{ if .Values.templateFilePath }}
            - '--template-file="{{ .Values.templateFilePath }}"'
            {{ end }}
            {{ if .Values.trustedHeader }}
            - '--trusted-header="{{ .Values.trustedHeader }}"'
            {{ end }}
          ports:
            - name: http
              containerPort: {{ .Values.port }}
              protocol: TCP
          volumeMounts:
            - mountPath: /tools
              name: tools-volume
          {{ if .Values.useGeoDb }}
            - mountPath: /db
              name: db-volume
            - mountPath: /db-shared
              name: db-shared-volume
          {{ end }}
          livenessProbe:
            exec:
              command:
                - '/tools/liveness.sh'
                - '{{ .Values.port }}'
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
      {{ if .Values.useGeoDb }}
      initContainers:
        - name: {{ .Chart.Name }}-init-db
          image: busybox
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/tools/init-db.sh"]
          volumeMounts:
            - mountPath: /db
              name: db-volume
            - mountPath: /db-shared
              name: db-shared-volume
            - mountPath: /tools
              name: tools-volume
      {{ end }}
      volumes:
        - name: tools-volume
          configMap:
            name: {{ template "echoip.fullname" . }}-tools
            defaultMode: 0744
        {{ if .Values.useGeoDb }}
        - name: db-volume
          emptyDir: {}
        - name: db-shared-volume
          persistentVolumeClaim:
            claimName: {{ template "echoip.fullname" . }}-db
        {{ end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
