apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "echoip.fullname" . }}
  labels:
    app: {{ template "echoip.name" . }}
    chart: {{ template "echoip.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingressType }}
    {{ if .Values.ingress_annotations }}
{{ toYaml .Values.ingress_annotations | indent 4 }}
    {{ end }}
spec:
  ingressClassName: {{ .Values.ingressType }}
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
        - backend:
            name: {{ template "echoip.fullname" . }}
            port:
              number: {{ .Values.service.port }}
          path: /
          pathType: Prefix                
  {{ if .Values.tls }}              
  tls:
  - hosts:
    - {{ .Values.host }}
    secretName: {{ .Values.host }}-tls
  {{ end }}