apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "echoip.fullname" . }}-db
  labels:
    app: {{ template "echoip.name" . }}
    chart: {{ template "echoip.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: 1Gi
